result_handler:
  type: SOCKET
  socket:
    port: 60060
    host: 127.0.0.1

instances:
  - source:
      type: IP_CAMERA
      url: rtsp://admin:Catab234@10.10.0.85:554/1
      device: "CAMERA-1"
    runners:
      - name: yolov5m - Object detection with 80 classes (Fast)
        type: yolov5m
        configuration: yolov5m.json
        class: Yolov5mRunner
        priority: 10
      - name: Cigarette Detector
        type: cigarette_detector
        configuration: cigarette_detector.json
        class: CigaretteDetectorRunner
        priority: 10

  - source:
    type: CAMERA
      url: https://www.youtube.com/watch?v=8Ts9M2f11HE
      device: "DEVICE-YOUTUBE"
      cam_gear_options:
        CAP_PROP_FRAME_WIDTH: 320
        CAP_PROP_FRAME_HEIGHT: 240
        CAP_PROP_FPS: 10
    runners:
      - name: yolov5m - Object detection with 80 classes (Fast)
        type: yolov5m
        configuration: yolov5m.json
        class: Yolov5mRunner
        priority: 10
      - name: Person Counter
        type: personcounter
        configuration: person_counter.json
        class: person_counter_runner
        priority: 100
