
video_source:
  type: VIDEO_FILE
  file_path: data/duygu2.mp4
  url:

connectors:
#  -
#    name: drivermonitor Camera Runner
#    type: drivermonitor
#    configuration: drivermonitor.json
#  -
#    name: socialdistance Camera Runner
#    type: socialdistance
#    configuration: socialdistance.json
  -
    name: emotionanalysis Camera Runner
    type: emotionanalysis
    configuration: emotionanalysis.json

